const apiRoutes = {
  login: "/auth/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  me: "/auth/me",
  role: "/role",
  forgotPassword: "/auth/password/reset",
  resetPassword: "/auth/password/confirm",
  admin: {
    overview: "/admin/overview",
    study_group: "/admin/study_group",
    question: "/admin/question",
    user: "/admin/user",
    create_user: "/auth/register",
    subject: "/subject",
    assignment: "/admin/assignment",
    exam: "/admin/exam",
    notification: "/admin/notification",
    permission: "/admin/permission",
  },
  teacher: {
    overview: "/teacher/overview",
    study_group: "/study-group/teacher",
    study_group_detail: "/study-group/detail",
    question: "/teacher/question",
    user: "/teacher/user",
    module: "/teacher/module",
    assignment: "/teacher/assignment",
    exam: "/teacher/exam",
    notification: "/teacher/notification",
  },
  student: {
    overview: "/student/overview",
    study_group: "/student/study_group",
    exam: "/student/exam",
    notification: "/student/notification",
  },
}
export default apiRoutes
