const apiRoutes = {
  login: "/auth/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  me: "/auth/me",
  role: "/role",
  forgotPassword: "/auth/password/reset",
  resetPassword: "/auth/password/confirm",
  googleVerify: "/auth/google/verify",
  googleConfirm: "/auth/google/confirm",
  difficultyLevel: "/difficulty-levels",
  admin: {
    overview: "/admin/overview",
    study_group: "/admin/study-groups",
    question: "/questions",
    user: "/admin/users",
    create_user: "/auth/register",
    subject: "/subject",
    academic_year: "/academic-years",
    semester: "/admin/semesters",
    assignment: "/admin/assignment",
    exam: "/admin/exam",
    notification: "/admin/notification",
    permission: "/admin/permission",
  },
  teacher: {
    overview: "/teacher/overview",
    study_group: "/teacher/study-groups",
    study_group_detail: "/study-group/detail",
    question: "/questions",
    user: "/teacher/user",
    module: "/teacher/module",
    assignment: "/teacher/assignment",
    exam: "/exams",
    point_scale: "/point-scales/all",
    notification: "/teacher/notification",
  },
  student: {
    overview: "/student/overview",
    study_group: "/student/study_group",
    exam: "/student/exam",
    notification: "/student/notification",
  },
}
export default apiRoutes
