const path = {
  SERVER_URL: 'https://successful-laura-tsondev-c5a7fe4d.koyeb.app',
  SOCKET_URL: 'https://successful-laura-tsondev-c5a7fe4d.koyeb.app/events',
  // SERVER_URL: 'http://localhost:3000',
  // SOCKET_URL: 'http://localhost:3000/events',
  PUBLIC: '/',
  HOME: '',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  PROFILE: '/profile',
  ACCESS_DENIED: '/access-denied',
  OTP_CONFIRMATION: '/otp-confirmation',
  EXAM_DETAIL: '/exam-detail/:exam_id',
  ADMIN: {
    OVERVIEW: '/admin/overview',
    STUDY_GROUP: '/admin/study_group',
    QUESTION: '/admin/question',
    USER: '/admin/user',
    SUBJECT: '/admin/subject',
    YEAR_SEMESTER: '/admin/year_semester',
    ASSIGNMENT: '/admin/assignment',
    EXAM: '/admin/exam',
    PERMISSTION_ROLE: '/admin/permission_role',
    PERMISSTION_USER: '/admin/permission_user',
    ASSIGN_TEACHER: '/admin/assign_teacher',
  },
  TEACHER: {
    OVERVIEW: '/teacher/overview',
    STUDY_GROUP: '/teacher/study_group',
    QUESTION: '/teacher/question',
    QUESTION_BANK: '/teacher/question_bank',
    USER: '/teacher/user',
    MODULE: '/teacher/module',
    MODULE_DETAIL: '/teacher/module/detail',
    SUBJECT: '/teacher/subject',
    ASSIGNMENT: '/teacher/assignment',
    EXAM: '/teacher/exam',
    EXAM_ROOM_TEACHER: '/teacher/exam-room-teacher',
    EXAM_RESULT: '/teacher/exam-result',
    EXAM_RESULT_DETAIL: '/teacher/exam-result/:exam_id/study-group/:study_group_id',
    APPROVE_QUESTION: '/teacher/approve-question',
    APPROVE_EXAM: '/teacher/approve-exam',
    NOTIFICATION: '/teacher/notification',
  },
  STUDENT: {
    OVERVIEW: '/student/overview',
    STUDY_GROUP: '/student/study_group',
    EXAM: '/student/exam',
    EXAM_LIST: '/student/exam_list',
    EXAM_RESULTS: '/student/exam_results',
    EXAM_CALENDAR: '/student/exam_calendar',
    EXAM_ROOM_STUDENT: '/student/exam-room-student',
    CREATE_STUDENT_SOCKET: '/student/create-student-socket',
  },
};

export default path;
